---
title: "Syphils/ARV"
output: html_document
---

```{r pkgs,warning=FALSE,message=FALSE}
library("ggplot2"); theme_set(theme_bw())
scale_colour_discrete <- function(...,palette="Set1") scale_colour_brewer(...,palette=palette)
scale_fill_discrete <- function(...,palette="Set1") scale_fill_brewer(...,palette=palette)
library("gridExtra")
library("plyr")  ## for ldply()
library("dplyr") ## for full_join()
library("reshape2")  ## for melt()
library("GGally")
library("knitr")
## devtools::install_github("lionel-/ggstance")
library("ggstance")
```


```{r index, echo = FALSE}

N <- c(1:9)
S.HIV <- c(1,4,7)
I.HIV <- c(2,5,8)
T.HIV <- c(3,6,9)
S.syph <- c(1:3)
I.syph <- c(4:6)
T.syph <- c(7:9)

```

## All plots


```{r load,echo=FALSE,message=FALSE}

load("syphData.rda")

comp.names <- c("SS", "IS", "TS", "SI", "II", "TI", "ST", "IT", "TT")

syphList <- list()
stateNames <- c("co", "HIV", "syph")
matNames <- c("highC", "lowC")

tvec <- syph_sim.co[,1]

for(m in stateNames){
	for(i in c(1:2)){
		syphList[[m]][[matNames[i]]] <- as.data.frame(get(paste0("syph_sim.",m))[,c(1,seq(from = (i+1), by = 2, length.out = 9))])
		colnames(syphList[[m]][[matNames[i]]]) <- c("time",comp.names)
	}
}

syphFrame <- melt(syphList[["co"]], id.vars = "time")

sumList <- prev_name <- sumFrame <- list()

prev_name[["co"]] <- c("N","S.HIV","I.HIV","T.HIV","S.syph","I.syph","T.syph")
prev_name[["HIV"]] <- c("S.HIV","I.HIV","T.HIV")
prev_name[["syph"]] <- c("S.syph","I.syph","T.syph")

for(s in stateNames){
	for(m in prev_name[[s]]){
		sumList[[s]][[m]] <- ldply(syphList[[s]],
			function(x) data.frame(time = tvec, value = rowSums(x[,get(m)+1])
		))
	}
	sumFrame[[s]] <- melt(sumList[[s]], id.vars = c("time", ".id"))
	
	if(s != c("Co")){
		sumFrame[[s]]$L1 <-
			factor(sumFrame[[s]]$L1, levels = prev_name[[s]])
	}
}
```


```{r allPlot, fig.width = 10, fig.height = 10, echo = FALSE}

library("grid")

g.co <- ggplot(syphFrame, aes(time, value, col = L1)) +
	geom_line() +
	theme(legend.position="none",
		panel.margin = unit(1, "lines")) +
	labs(x = NULL, y = NULL) +
	facet_wrap(~variable, scale = "free")

g.HIV <- ggplot(subset(sumFrame[["co"]], L1 %in% c("S.HIV","I.HIV", "T.HIV")), aes(time, value, col = .id)) +
	geom_line() +
	theme(legend.position="none",
		panel.margin = unit(1, "lines")) +
	labs(x = NULL, y = NULL)+
	facet_wrap(~L1, scale = "free")

g.syph <- ggplot(subset(sumFrame[["co"]], L1 %in% c("S.syph","I.syph", "T.syph")), aes(time, value, col = .id)) +
	geom_line() +
	theme(legend.position="none",
		panel.margin = unit(1, "lines")) +
	labs(x = NULL, y = NULL)+
	facet_wrap(~L1, scale = "free", ncol = 1)

lay <- rbind(c(1,2,2,2),
	c(3,4,4,4),
	c(3,4,4,4),
	c(3,4,4,4))

library("gtable")

legend <- gtable_filter(ggplot_gtable(ggplot_build(g.co + theme(legend.position="right"))), "guide-box")

lwidth <- sum(legend$width)

grid.arrange(arrangeGrob(grid.rect(gp=gpar(col="white")), g.HIV, g.syph, g.co, ncol = 2,
	layout_matrix = lay), legend, 
	widths=unit.c(unit(1, "npc") - lwidth, lwidth), nrow=1)

```

## Total population

```{r population}

ggplot(subset(sumFrame[["co"]], L1 %in% c("N")), aes(time, value, col = .id)) +
	ylim(0, 1) +
	geom_line() +
	facet_wrap(~L1, scale = "free")

```

##Separate cases

```{r prevalence,fig.width = 10}

ggplot(sumFrame[["HIV"]], aes(time, value, col = .id)) +
	geom_line() +
	facet_wrap(~L1, scale = "free")
ggplot(sumFrame[["syph"]], aes(time, value, col = .id)) +
	geom_line() +
	facet_wrap(~L1, scale = "free")

```

